# Generated by Django 4.1.4 on 2022-12-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='turn',
        ),
    ]
