# Generated by Django 4.1.4 on 2022-12-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_boardmodel_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='difficulty',
            field=models.IntegerField(default=100, max_length=100),
        ),
    ]
