# Generated by Django 4.1.4 on 2022-12-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_computermodel_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='trainingMode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='difficulty',
            field=models.IntegerField(default=100),
        ),
    ]
