# Generated by Django 4.1.4 on 2022-12-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gamemodel_trainingmode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
